version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_exercise_app
    ports:
      - "6000:6000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./resources/config.json:/app/resources/config.json

  postgres:
    image: postgres:14.1-alpine
    container_name: backend_exercise_db
    environment:
      - POSTGRES_DB=backend_exercise
      - POSTGRES_USER=backend_exercise_user
      - POSTGRES_PASSWORD=backend_exercise_password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U backend_exercise_user" ]
      interval: 10s
      timeout: 5s
      retries: 5
